# Generated by Django 3.2.8 on 2021-11-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_review_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
